// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface IReceiver {
    function onReport(
        bytes calldata reportContext,
        bytes calldata rawReport
    ) external;
}

/**
 * @title MockForwarderV2
 * @notice Mock implementation of Chainlink Keystone Forwarder.
 * Allows simulating the exact interface expected by the CRE CLI.
 *
 * Production: CRE DON → Real Keystone Forwarder → Verity.onReport
 * Hackathon: User/CRE CLI → MockForwarderV2.report → Verity.onReport
 *
 * Verity must be deployed with CRE_ROLE = address(this) so onlyCre modifier allows this contract.
 */
contract MockForwarderV2 {
    event ReportForwarded(
        address indexed receiver,
        bytes rawReport,
        bytes reportContext
    );

    /**
     * @notice Mock report function, mirrors the real KeystoneForwarder.
     * Skips signature verification.
     * @param receiver The address of the consumer contract (e.g. Verity)
     * @param rawReport The raw report bytes generated by the workflow
     * @param reportContext Contextual metadata about the report
     */
    function report(
        address receiver,
        bytes calldata rawReport,
        bytes calldata reportContext,
        bytes[] calldata /* signatures */
    ) external {
        if (receiver == address(0)) revert("Invalid receiver");

        // Forward to receiver using the expected hook
        IReceiver(receiver).onReport(reportContext, rawReport);

        emit ReportForwarded(receiver, rawReport, reportContext);
    }
}
